name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
